<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="RTZ 2 (зима)">
<General productName="Vugen" productVer="2020" os="" host="DESKTOP-SUPA3AD"><DocLocation><![CDATA[C:\Users\Simon\Desktop\IPR\WebServices6]]></DocLocation></General>
<Doc rID="T1"   productName= "Vugen"  >
<DName><![CDATA[WebServices6]]></DName>
<Res><![CDATA[result1]]></Res>
<Action rID="T2">
<AName><![CDATA[vuser_init]]></AName>
<Step rID="T3">
<Obj plainTxt="False" ><![CDATA[LatLonListCityNames_108]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Web service call was successful</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[10.06.2020 - 11:12:20]]></Time>
<TimeTick>1591776740</TimeTick>
<Step rID="T4">
<Obj plainTxt="False" ><![CDATA[HTTP Traffic]]></Obj>
<Details plainTxt="False" ><![CDATA[HTTP Traffic]]></Details>
<Time><![CDATA[10.06.2020 - 11:12:20]]></Time>
<TimeTick>1591776740</TimeTick>
<NodeArgs eType="General" icon="3" nRep="7" >
<Disp><![CDATA[HTTP Traffic]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration1\t1_http.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="General" icon="3" nRep="6" status="Passed" >
<Disp><![CDATA[LatLonListCityNames_108]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration1\t0_web_service_call.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Summary sTime="10.06.2020 - 11:12:18" eTime="10.06.2020 - 11:12:21" passed="1" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="5" status="Passed" >
<Disp><![CDATA[vuser_init Summary]]></Disp>
</NodeArgs>
</Action>
<DIter rID="T5" iterID="1" >
<Action rID="T6">
<AName><![CDATA[Action]]></AName>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[NDFDgen_105]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Web service call was successful</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[10.06.2020 - 11:12:22]]></Time>
<TimeTick>1591776742</TimeTick>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[HTTP Traffic]]></Obj>
<Details plainTxt="False" ><![CDATA[HTTP Traffic]]></Details>
<Time><![CDATA[10.06.2020 - 11:12:22]]></Time>
<TimeTick>1591776742</TimeTick>
<NodeArgs eType="General" icon="3" nRep="12" >
<Disp><![CDATA[HTTP Traffic]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration1\t2_http.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="General" icon="3" nRep="11" status="Passed" >
<Disp><![CDATA[NDFDgen_105]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration1\t1_web_service_call.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Summary sTime="10.06.2020 - 11:12:21" eTime="10.06.2020 - 11:12:22" passed="1" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="10" status="Passed" >
<Disp><![CDATA[Action Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="4" nRep="9" status="Passed" >
<Disp><![CDATA[WebServices6 Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T9" iterID="2" >
<Action rID="T10">
<AName><![CDATA[Action]]></AName>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[NDFDgen_105]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Web service call was successful</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[10.06.2020 - 11:12:23]]></Time>
<TimeTick>1591776743</TimeTick>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[HTTP Traffic]]></Obj>
<Details plainTxt="False" ><![CDATA[HTTP Traffic]]></Details>
<Time><![CDATA[10.06.2020 - 11:12:23]]></Time>
<TimeTick>1591776743</TimeTick>
<NodeArgs eType="General" icon="3" nRep="18" >
<Disp><![CDATA[HTTP Traffic]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration2\t2_http.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="General" icon="3" nRep="17" status="Passed" >
<Disp><![CDATA[NDFDgen_105]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration2\t2_web_service_call.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Summary sTime="10.06.2020 - 11:12:22" eTime="10.06.2020 - 11:12:23" passed="1" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="16" status="Passed" >
<Disp><![CDATA[Action Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="4" nRep="15" status="Passed" >
<Disp><![CDATA[WebServices6 Iteration 2 (Row 2)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T13" iterID="3" >
<Action rID="T14">
<AName><![CDATA[Action]]></AName>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[NDFDgen_105]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Web service call was successful</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[10.06.2020 - 11:12:24]]></Time>
<TimeTick>1591776744</TimeTick>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[HTTP Traffic]]></Obj>
<Details plainTxt="False" ><![CDATA[HTTP Traffic]]></Details>
<Time><![CDATA[10.06.2020 - 11:12:24]]></Time>
<TimeTick>1591776744</TimeTick>
<NodeArgs eType="General" icon="3" nRep="24" >
<Disp><![CDATA[HTTP Traffic]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration3\t2_http.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="General" icon="3" nRep="23" status="Passed" >
<Disp><![CDATA[NDFDgen_105]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration3\t2_web_service_call.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Summary sTime="10.06.2020 - 11:12:23" eTime="10.06.2020 - 11:12:25" passed="1" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="22" status="Passed" >
<Disp><![CDATA[Action Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="4" nRep="21" status="Passed" >
<Disp><![CDATA[WebServices6 Iteration 3 (Row 3)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T17" iterID="4" >
<Action rID="T18">
<AName><![CDATA[Action]]></AName>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[NDFDgen_105]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Web service call was successful</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[10.06.2020 - 11:12:26]]></Time>
<TimeTick>1591776746</TimeTick>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[HTTP Traffic]]></Obj>
<Details plainTxt="False" ><![CDATA[HTTP Traffic]]></Details>
<Time><![CDATA[10.06.2020 - 11:12:26]]></Time>
<TimeTick>1591776746</TimeTick>
<NodeArgs eType="General" icon="3" nRep="30" >
<Disp><![CDATA[HTTP Traffic]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration4\t2_http.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="General" icon="3" nRep="29" status="Passed" >
<Disp><![CDATA[NDFDgen_105]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration4\t2_web_service_call.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Summary sTime="10.06.2020 - 11:12:25" eTime="10.06.2020 - 11:12:26" passed="1" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="28" status="Passed" >
<Disp><![CDATA[Action Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="4" nRep="27" status="Passed" >
<Disp><![CDATA[WebServices6 Iteration 4 (Row 4)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T21" iterID="5" >
<Action rID="T22">
<AName><![CDATA[Action]]></AName>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[NDFDgen_105]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Web service call was successful</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[10.06.2020 - 11:12:27]]></Time>
<TimeTick>1591776747</TimeTick>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[HTTP Traffic]]></Obj>
<Details plainTxt="False" ><![CDATA[HTTP Traffic]]></Details>
<Time><![CDATA[10.06.2020 - 11:12:27]]></Time>
<TimeTick>1591776747</TimeTick>
<NodeArgs eType="General" icon="3" nRep="36" >
<Disp><![CDATA[HTTP Traffic]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration5\t2_http.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="General" icon="3" nRep="35" status="Passed" >
<Disp><![CDATA[NDFDgen_105]]></Disp>
<BtmPane vType="HTMLSNSH" >
<Path><![CDATA[\Iteration5\t2_web_service_call.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Summary sTime="10.06.2020 - 11:12:26" eTime="10.06.2020 - 11:12:27" passed="1" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="34" status="Passed" >
<Disp><![CDATA[Action Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="4" nRep="33" status="Passed" >
<Disp><![CDATA[WebServices6 Iteration 5 (Row 5)]]></Disp>
</NodeArgs>
</DIter>
<Action rID="T25">
<AName><![CDATA[vuser_end]]></AName>
<Summary sTime="10.06.2020 - 11:12:27" eTime="10.06.2020 - 11:12:27" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="39" >
<Disp><![CDATA[vuser_end Summary]]></Disp>
</NodeArgs>
</Action>
<Summary sTime="10.06.2020 - 11:12:18" eTime="10.06.2020 - 11:12:28" passed="6" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="4" status="Passed" >
<Disp><![CDATA[Test WebServices6 Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>